global using OpenQA.Selenium.Firefox;
global using BotHelper.ClientManager;
global using BotHelper.Model;
global using BotHelper.Model.Clients;
global using OpenQA.Selenium;
global using OpenQA.Selenium.Firefox;
global using Telegram.Bot;
global using Telegram.Bot.Polling;
global using Telegram.Bot.Types;